#!/bin/bash
# Autor: marten
#skriptinimi on yl2
# Kirjeldus: Skript kuvab kasutajale menüü, palub valida toiduvaliku ning väljastab vastava sõnumi.

echo "Palun vali menüüst üks järgmistest valikutest:"
echo "1) liha ja kartulid"
echo "2) kala ja krõpsud"
echo "3) supp ja salat"

read -p "Tee oma valik (1 või 2 või 3): " valik

case $valik in
  1)
    echo "Väga maitsev, aga jälgi oma tervist!"
    echo "Head isu!"
    ;;
  2)
    echo "Brititoit on maisev!"
    echo "Head isu!"
    ;;
  3)
    echo "Nii tervislik ja igav..."
    echo "Head isu!"
    ;;
  *)
    echo "Vale valik! Palun sisesta number 1, 2 või 3."
    ;;
esac
