#!/bin/bash
# Skript ütleb, mis aastaajal ollakse vastavalt sisestatud kuu numbrile.

echo -n "Sisesta kuu number: "
read kuu

if ! [[ "$kuu" =~ ^[1-9]$|^1[0-2]$ ]]
then
    echo "Vigane kuu number! Palun sisesta number 1 kuni 12."
    exit 1
fi

if [ $kuu -eq 12 ] || [ $kuu -eq 1 ] || [ $kuu -eq 2 ]
then
    echo "Praegu on talv"
elif [ $kuu -ge 3 ] && [ $kuu -le 5 ]
then
    echo "Praegu on kevad"
elif [ $kuu -ge 6 ] && [ $kuu -le 8 ]
then
    echo "Praegu on suvi"
elif [ $kuu -ge 9 ] && [ $kuu -le 11 ]
then
    echo "Praegu on sügis"
fi
