#!/bin/bash
# Skript tervitab kasutajat automaatselt määratud kellaaja põhjal ja lisab tervitusele kasutajanime.

# Võta kasutajanimi keskkonnamuutujast USER
kasutaja=$USER

# Võta süsteemi aeg tundides (00-23)
tund=$(date +%H)
# Eemalda juhtivad nullid (nt "07" -> "7")
tund=$((10#$tund))

if [ $tund -ge 6 -a $tund -lt 12 ]
then
    echo "Tere hommikust, $kasutaja!"
elif [ $tund -ge 12 -a $tund -lt 18 ]
then
    echo "Tere päevast, $kasutaja!"
elif [ $tund -ge 18 -a $tund -lt 22 ]
then
    echo "Tere õhtust, $kasutaja!"
elif [ $tund -ge 22 -o $tund -lt 6 ]
then
    echo "Head ööd, $kasutaja!"
else
    echo "Vigane aeg, $kasutaja!"
fi
